### ISSUE TITLE
Tons of warnings in AsciiKeyMap

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#10]
```
[1/181] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/AsciiKeyMap.cpp.obj
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
 };
 ^
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
```

**Comment by jamesadevine** [comment]
What version of gcc?

James.

On 23 Jan 2018, at 19:58, Peli de Halleux <notifications@github.com<mailto:notifications@github.com>> wrote:


[1/181] Building CXX object libraries/codal-core/CMakeFiles/codal-core.dir/source/drivers/AsciiKeyMap.cpp.obj
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
 };
 ^
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::seq' [-Wmissing-field-initializers]
../libraries/codal-core/source/drivers/AsciiKeyMap.cpp:554:1: warning: missing initializer for member 'codal::KeySequence::length' [-Wmissing-field-initializers]

**Comment by jamesadevine** [comment]
I'm not seeing these warnings, I'm on GCC 7.2

**Comment by jamesadevine** [comment]
Fixed.

**Comment by jamesadevine** [comment]
Tagged under [#v1.3.4](https://github.com/lancaster-university/codal-circuit-playground/releases/tag/v1.3.4)
