### ISSUE TITLE
codal-core not building in docker

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#11]
```
In file included from /home/build/prjclone/libraries/codal-core/source/drivers/AsciiKeyMap.cpp:1:0:
/home/build/prjclone/libraries/codal-core/./inc/drivers/AsciiKeyMap.h:1:20: fatal error: KeyMap.h: No such file or directory
 #include "KeyMap.h"
```

```
Creating libraries folder
Cloning into: https://github.com/lancaster-university/codal-circuit-playground
Cloning into 'codal-circuit-playground'...
Checking out branch: v1.3.2
HEAD is now at e595933... Snapshot v1.3.2
[1;35mSet target: codal-circuit-playground [m
Using target-locked.json
[1;34mTargeting codal-circuit-playground[m
Installing dependencies...
Cloning into: https://github.com/lancaster-university/codal-core
Cloning into 'codal-core'...
Checking out branch: d5869d5ebe7c69754065b0c46c9db09dd96aa6fe
HEAD is now at d5869d5... Merge pull request #9 from adafruit/master
Cloning into: https://github.com/lancaster-university/mbed-classic
Cloning into 'mbed-classic'...
Checking out branch: 9100ba3f433129b176c535311afb5fad3b2f9e26
HEAD is now at 9100ba3... Use alt SERCOM for PA12 (to allow SPI on Zero-like boards)
Cloning into: https://github.com/lancaster-university/codal-samd21
Cloning into 'codal-samd21'...
Checking out branch: 87e1b872c041c9b21f575a1d6f3970c7e0a60d7c
HEAD is now at 87e1b87... Remove clock init code from USB.cpp (it's now in CPX target)
Cloning into: https://github.com/lancaster-university/codal-mbed
Cloning into 'codal-mbed'...
Checking out branch: 52b5a26ed40a6e8d33a8f06b7bec9764730045ef
HEAD is now at 52b5a26... Fix Pin reference in SPI
[1;32mUsing library: codal-circuit-playground[m
[1;32mUsing library: codal-core[m
[1;32mUsing library: mbed-classic[m
[1;32mUsing library: codal-samd21[m
[1;32mUsing library: codal-mbed[m
In file included from /home/build/prjclone/libraries/codal-core/source/drivers/AsciiKeyMap.cpp:1:0:
/home/build/prjclone/libraries/codal-core/./inc/drivers/AsciiKeyMap.h:1:20: fatal error: KeyMap.h: No such file or directory
 #include "KeyMap.h"
                    ^
compilation terminated.
```

**Comment by jamesadevine** [comment]
Yeah saw that on travis. Will fix later


James.

On 23 Jan 2018, at 20:03, Peli de Halleux <notifications@github.com<mailto:notifications@github.com>> wrote:


In file included from /home/build/prjclone/libraries/codal-core/source/drivers/AsciiKeyMap.cpp:1:0:
/home/build/prjclone/libraries/codal-core/./inc/drivers/AsciiKeyMap.h:1:20: fatal error: KeyMap.h: No such file or directory
 #include "KeyMap.h"


Creating libraries folder
Cloning into: https://github.com/lancaster-university/codal-circuit-playground
Cloning into 'codal-circuit-playground'...
Checking out branch: v1.3.2
HEAD is now at e595933... Snapshot v1.3.2
�[1;35mSet target: codal-circuit-playground �[m
Using target-locked.json
�[1;34mTargeting codal-circuit-playground�[m
Installing dependencies...
Cloning into: https://github.com/lancaster-university/codal-core
Cloning into 'codal-core'...
Checking out branch: d5869d5ebe7c69754065b0c46c9db09dd96aa6fe
HEAD is now at d5869d5... Merge pull request #9 from adafruit/master
Cloning into: https://github.com/lancaster-university/mbed-classic
Cloning into 'mbed-classic'...
Checking out branch: 9100ba3f433129b176c535311afb5fad3b2f9e26
HEAD is now at 9100ba3... Use alt SERCOM for PA12 (to allow SPI on Zero-like boards)
Cloning into: https://github.com/lancaster-university/codal-samd21
Cloning into 'codal-samd21'...
Checking out branch: 87e1b872c041c9b21f575a1d6f3970c7e0a60d7c
HEAD is now at 87e1b87... Remove clock init code from USB.cpp (it's now in CPX target)
Cloning into: https://github.com/lancaster-university/codal-mbed
Cloning into 'codal-mbed'...
Checking out branch: 52b5a26ed40a6e8d33a8f06b7bec9764730045ef
HEAD is now at 52b5a26... Fix Pin reference in SPI
�[1;32mUsing library: codal-circuit-playground�[m
�[1;32mUsing library: codal-core�[m
�[1;32mUsing library: mbed-classic�[m
�[1;32mUsing library: codal-samd21�[m
�[1;32mUsing library: codal-mbed�[m
In file included from /home/build/prjclone/libraries/codal-core/source/drivers/AsciiKeyMap.cpp:1:0:
/home/build/prjclone/libraries/codal-core/./inc/drivers/AsciiKeyMap.h:1:20: fatal error: KeyMap.h: No such file or directory
 #include "KeyMap.h"
                    ^
compilation terminated.

**Comment by jamesadevine** [comment]
Fixed

**Comment by jamesadevine** [comment]
Tagged under [#v1.3.4](https://github.com/lancaster-university/codal-circuit-playground/releases/tag/v1.3.4)
