### ISSUE TITLE
Missing setListenerDeletionCallback

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#121]
https://github.com/lancaster-university/microbit-dal/blob/9164922a519aa213a565cbf2abaa2cf4debf4977/inc/core/EventModel.h#L144

**Comment by microbit-carlos** [comment]
Added in https://github.com/lancaster-university/codal-core/commit/0740e234c9e4c1361c5f1db9c8870a6901cbcae8.
