### ISSUE TITLE
JACDAC update or remove?

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#125]
Do we still need JACDAC in CODAL?

**Comment by finneyj** [comment]
There's a fair bit of code lurking in codal-core at the moment... but the stack isreally in TypeScript now right?

**Comment by mmoskal** [comment]
Yes. I don't think we have cycles to update this, so I would say just remove.

The SingleWireSerial is still used by MakeCode as the basis of the C+TS stack.

**Comment by pelikhan** [comment]
Voting to remove and maybe bring back later.
