### ISSUE TITLE
`ManagedBuffer::shift` overwrites the entire buffer with zero on a large shift value

### ISSUE THREAD

**Issue by c272** [lancaster-university/codal-core#156]
If given a shift value larger than or equal to the length of the buffer region being shifted, `ManagedBuffer` will simply fill the entire buffer with zero, rather than the intended buffer region:

https://github.com/lancaster-university/codal-core/blob/f08eb30d75d0a786229344431177aa0e1c67c0a3/source/types/ManagedBuffer.cpp#L306-L309

This can be reproduced with the following MRE:
```cpp
#include <MicroBit.h>
MicroBit uBit;

int main() {
    uBit.init();
    ManagedBuffer buf(32);

    //Fill some unrelated very important bytes with data.
    buf.fill(0xAA, 0, sizeof(int));

    //Fill some other region, and then attempt a large shift.
    buf.fill(0xBB, 16, 16);
    buf.shift(1000, 16, 16);

    //Our very important data has now been overwritten with zero...
    int* important_data = reinterpret_cast<int*>(buf.getBytes());
    while (true)
        uBit.display.scroll(*important_data);
}
```

This seems like a simple fix, and seems to work fine when L306-309 are changed to instead read:
```cpp
if (offset <= -len || offset >= len) {
        fill(0, start, len);
        return;
}
```

**Comment by finneyj** [comment]
Many thanks @c272!

That's a good catch. I agree the current behaviour seems rather counter intuitive, and your suggested fix looks good.

Would you like to work up a PR and contribute?

**Comment by c272** [comment]
No problem, I've submitted a PR at #157.
