### ISSUE TITLE
Add JDEvent type instead Event

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#36]
The Event has a 64bit timestamp that also gets sent over the network. Can we use a dedicated struct here?
https://github.com/lancaster-university/codal-core/blob/3f1a2e43c226eb73df75306e6629eadd9d365662/source/JACDAC/JDMessageBusDriver.cpp#L129

**Comment by jamesadevine** [comment]
The remainder of the packet is filled with noise regardless, why reduce data resolution by removing the timestamp?

I'm more than happy to introduce a struct although it doesn't seem necessary to me given that we have the Event struct already.

**Comment by pelikhan** [comment]
It would be easier for maintenance to have a JDEvebt struct
