### ISSUE TITLE
Global events for JACDAC

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#47]
We currently have events per driver in jacdac. Would be nice to have "top level" events:

- jacdac bus connected / disconnected
- driver changed (connected or disconnected)

**Comment by pelikhan** [comment]
Whenever any driver changes state (connect, disconnect, etc....) so that I can update my UI. Unless this is too chatty.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesadevine** [comment]
Bus connected / disconnected is now available as an event. Listen to it via JACDAC's id and the event values 

```
#define JD_SERIAL_EVT_BUS_CONNECTED    5
#define JD_SERIAL_EVT_BUS_DISCONNECTED 6
```

I've also added a polling API to JACDAC: `isConnected()`. Returns true if the bus is fine, false if not.
