### ISSUE TITLE
Status LED support in JACDAC

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#48]
Just like the RJ45 ports, we could support an optional jacdac LED to display the status of the bus on the device.

**Comment by jamesadevine** [comment]
If you construct the JACDAC class with an optional LED, it will use this LED to display the state of the bus.

When the bus is held lo, the led will be off, when it is operating normally, the led will be on.

**Comment by jamesadevine** [comment]
```jacdac(sws, io.ledRed)```
