### ISSUE TITLE
Add function to list all drivers in protocol (jacdac)

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#49]
I need to send the entire state of each driver "device" to MakeCode side to create a debugger UI. Can you add a function to JDProtocol to list drivers?
- [ ] list all drivers
- [ ] dump "device" state of the driver

**Comment by pelikhan** [comment]
Pretty much make it public.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesadevine** [comment]
I'm not sure you can be trusted... :wink:

Yup, will do!

**Comment by pelikhan** [comment]
Also need access to the device field.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesadevine** [comment]
Will add an accessor for that.

**Comment by jamesadevine** [comment]
`JDProtocol::drivers` is now public.

Each driver now has a `getState` member function.
