### ISSUE TITLE
Device hangs after an hour

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#5]
James already found the issue but I could not resist assigning a bug :)

**Comment by jamesadevine** [comment]
@pelikhan @abchatra @riknoll @tballmsft @mmoskal @finneyj 

New snapshot: v1.2.7 https://github.com/lancaster-university/codal-circuit-playground/commit/fb796d9d7599e6f97f701e91f2f2f5bec378be4a

This should provide a temporary fix for timer overflow, pending a more graceful handling of timer overflow in the future.

**Comment by riknoll** [comment]
Thanks @jamesadevine!

**Comment by pelikhan** [comment]
I'm seeing a constant slowdown on a loop that pauses.
```
let i = 0;
while (true) {
    let start = control.millis();
    loops.pause(50)
    let end = control.millis();
    if (i++ % 20 == 0)
        serial.writeValue("t", end - start);
}
```

**Comment by mmoskal** [comment]
I'm also seeing problems in my new clock drift resistant IR code - I think because i bump the TC4 interrupt used by mbed timer to priority 1 - i need The EIC to have priority over TC4 because otherwise timings of pin pulses are junk. Anyways the result is that scheduler_tick stops being called after some time.

James, do you fancy a custom SAMD timer? ;)

**Comment by pelikhan** [comment]
It reproes in C++:
```
int main()
{
    int status = 0;
    while(1)
    {
        cplay.io.led.setDigitalValue(status);
        cplay.sleep(100);
        status = !status;
    }
}
```

**Comment by pelikhan** [comment]
@jamesadevine @finneyj FYi

**Comment by riknoll** [comment]
Not seeing that behavior with Grove Zero on latest CODAL. I'll leave it blinking an LED overnight and see what it looks like tomorrow.

**Comment by riknoll** [comment]
Never mind, I'm seeing the clock speed up significantly when toggling the LED every 100 ms. The board is connected to USB.

**Comment by pelikhan** [comment]
Speed up or slow down?

**Comment by jamesadevine** [comment]
Michal, could you surmise your running theory for me?

Is it that a change in interrupt priority has caused the timer interrupt to drop after an amount of time? The interrupt should be handled at some point in the future though, right?

James.

On 7 Nov 2017, at 02:49, Peli de Halleux <notifications@github.com<mailto:notifications@github.com>> wrote:


Speed up or slow down?

**Comment by jamesadevine** [comment]
Ok, isolated the issue in codal. Of course the problem is with the timer, it is specifically the following function: 

https://github.com/lancaster-university/codal-mbed/blob/master/source/MbedTimer.cpp#L68

This function is called when the timer is [determining the nextEvent to process](https://github.com/lancaster-university/codal-core/blob/master/source/driver-models/Timer.cpp#L231). After calling `syncRequest`, interrupts are enabled, and the timer code is interrupted (possibly by the EIC interrupt @mmoskal ?) and it never catches up...

I'm going to investigate what is interrupting the timer... Do we run with IR etc. @finneyj ? 

@mmoskal where did you apply the change to interrupt priorities?

**Comment by pelikhan** [comment]
My repro does not involve IR, maybe simpler to investigate?
https://github.com/lancaster-university/codal-core/issues/5#issuecomment-342324536

**Comment by jamesadevine** [comment]
Sorry @pelikhan, for clarification, the above are the results of my investigation of that basic sample. I have a fix without knowing the cause, I'm now investigating the cause to determine the best fix.

**Comment by pelikhan** [comment]
Thanks for jumping on this.

**Comment by mmoskal** [comment]
My theory was some race in the timer code, that would be triggered by an interrupt that kicks in. Unfortunately, the code goes through so many layers, I was unable to pin it down. I think it might have more to do with the TC3 interrupt I use for sending (which together with EIC runs at 0) pre-empting the TC4 (at 1) which is used by the embed timer.

I'm trying to get a simple repro with just TC3 and no IR, but failed so far. I'm only getting slowdown, not lockup.

**Comment by finneyj** [comment]
yes, it's definitely a race with the internal time state - the critical section we protected wasn't complete. We have a patch that resolves this issue - James is just tidying it up now. This is one really weird bug - I'm still not totally sure how this race causes such a cumulative error though

**Comment by jamesadevine** [comment]
@pelikhan @riknoll  https://github.com/lancaster-university/codal-circuit-playground/commit/fb2d6db40e6fa144a56f8ce522d15754f5534b5c

Try this one on for size, looks good on my scope.

@mmoskal As it was a race condition, we increased the time interrupts are disabled. In an effort to reduce churn on your IR code (as the timer disables all interrupts), we added a specialisation for cplay, that only disables TC4.  https://github.com/lancaster-university/codal-circuit-playground/commit/5d576f8e7346a5cfc49a15165bf9176915ddcb8e

**Comment by mmoskal** [comment]
I'm no longer seeing lock up with the IR sending (while still using the regular, not cplay, timer).

**Comment by pelikhan** [comment]
This issue looks fixed.

**Comment by finneyj** [comment]
Thanks Peli - yes, I believe so. I did see something similar on a micro:bit build based on mbed-os the other day (though i'm pretty sure it's something in the mbed-os timer driver). Please re-open if you see anything similar and I'll investigate.
