### ISSUE TITLE
Add status code in jacdac control packet

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#50]
For diagnosis purposes, jacdac control packets could also have a status code, similar to automation codes. This would allow a driver to expose a lightweight status.

Ok, battery low, malfunction, etc... highest code wins and gets transmitted

**Comment by pelikhan** [comment]
This could be crammed into the flags bitset.

**Comment by jamesadevine** [comment]
Good idea, unsure about flags as specific as "battery low" being exposed as part of each core control packet is necessary, but definitely more general flags would be useful.

**Comment by pelikhan** [comment]
IMO it's critical. JacDac is great until it does not work and its "debuggability" will greatly improve the experience of troubleshooting devices/networks.

**Comment by jamesadevine** [comment]
Absolutely, I don't know what this should look like – don't wanna rush decisions.

**Comment by jamesadevine** [comment]
This is in the spec
