### ISSUE TITLE
JacDacMessage enumeration types should match

### ISSUE THREAD

**Issue by teddyseyed** [lancaster-university/codal-core#53]
When creating jacdac messages, occasionally you will have scenarios where the value of a jacdac message on one device will not have the same jacdac message value on another device. This will affect how the listener will work on either side.

For example:

Device 1 can have

enum JacDacMessage {
    message1,
    SHAKE1,
    SHAKE2,
    SHAKE3
}

and Device 2 can have

enum JacDacMessage {
    SHAKE1,
}

**Comment by pelikhan** [comment]
This is a MakeCode issue. JacDac is not aware of the way we encode messages.
