### ISSUE TITLE
Use pointer for LED so that NULL can be passed in.

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#57]
https://github.com/lancaster-university/codal-core/blob/839e9bcf745b58a03b02ed497b1ac6791c82149d/inc/JACDAC/JACDAC.h#L181

**Comment by jamesadevine** [comment]
You have two constructors?

https://github.com/lancaster-university/codal-core/blob/839e9bcf745b58a03b02ed497b1ac6791c82149d/inc/JACDAC/JACDAC.h#L170

**Comment by pelikhan** [comment]
LookupPin is a runtime API so that I cannot pick the correct ctor at compile time.

**Comment by pelikhan** [comment]
Similar issue with the bridge... Can't unset the bridge once it is in.

**Comment by jamesadevine** [comment]
Done.
