### ISSUE TITLE
Seeing some oddly close serial numbers

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#68]
When connecting multiple devices, I am seeing more serial numbers than devices. 
To repro: connect multiple jacdac devices running a log broadcast service and list the serial numbers from the driver list.

**Comment by jamesadevine** [comment]
Were any of the two serial numbers the same but with different addresses?

**Comment by jamesadevine** [comment]
@pelikhan can I close?

**Comment by jamesadevine** [comment]
Not actually a bug.
