### ISSUE TITLE
Why is serial computed like this?

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#71]
I don't understand why it is OR with the driverclass. So each driver gets a unique serial number on the bus? I thaught the serial number was per device.

https://github.com/lancaster-university/codal-core/blob/ea674a6757b5a8de6da13c93c290b2f99b681141/inc/JACDAC/JDProtocol.h#L201

**Comment by jamesadevine** [comment]
This was intended as a way to uniquely identify a driver on a device. Perhaps just the device serial number will do for each driver... but let's say you're running two buttons, how do you know which button is which? They will have the same serial number, and different addresses.

Maybe this doesn't matter, or perhaps you put something extra in your control packets...

**Comment by pelikhan** [comment]
Would not help for buttons as they would have the same driver class. This is very confusing, can we just have serial number == device serial number ? Anything else is confusing.

**Comment by pelikhan** [comment]
Also you are increasing the risk of collision by loosing 16bits.
