### ISSUE TITLE
Model a device

### ISSUE THREAD

**Issue by jamesadevine** [lancaster-university/codal-core#78]
JACDAC should no longer send control packets for each driver, but rather provide a composition of drivers for a device. I propose the following revision to a `ControlPacket`:

```cpp
struct DriverInfo
    {
        uint8_t length;
        uint8_t address;        // the address assigned by the logic driver
        uint16_t flags;         // various flags, upper eight bits are reserved for control usage, lower 8 remain free for driver use.
        uint32_t driver_class;  // the class of the driver
        uint8_t payload[]; // optional additional data
    } __attribute((__packed__));
```

```cpp
struct ControlPacket
    {
        uint8_t packet_type;    // indicates the type of the packet, normally just HELLO
        uint32_t serial_number; // the "unique" serial number of the device.
        uint8_t data[]; // you would place driver info here for a HELLO_PACKET
    } __attribute((__packed__));
```

To justify this design change let me perform some back of the envelope calculations. Pretend we have variable sized packets, and we have 3 drivers running on a single device:

* currently each driver transmits a control packet every 500 ms
* control packets are currently 12 bytes, and if you add 4 for the JDPkt header, is 16 bytes.
* each control packet contains a serial number.

This means that 48 bytes are transmitted every 500 ms or 96 bytes every second, and 4 of those bytes are wasted sending duplicate serial_number information. At each baud you can compute the percentage of the bus spent on control packets for those three drivers:

* 0.07% at 1mb
* 0.15% at 500kb
* 0.3% at 250kb
* 0.6% at 125kb 

Using the new way of transmitting control packets:

* control packets are sent every 500ms, one per device.
* the control packet for 3 drivers, including the JDPkt header is now 36 bytes.

At each baud the picture looks like this:

* 0.04% at 1mb
* 0.1% at 500kb
* 0.16% at 250kb
* 0.32% at 125kb 

This also means that the bus will perform better at scale as the number of control packets sent is now proportional to the _devices_ on the bus and not the number of _drivers_.

These numbers do not include the time taken for bus arbitration, but by reducing the number of packets sent, we also reduce the time spent on bus arbitration.

@pelikhan @tballmsft @sehodges @mmoskal @finneyj thoughts?

**Comment by pelikhan** [comment]
Sounds good.
What is the relation between driverinfo and controlpacket?
Should we bump up the serialnumber number of bytes?

**Comment by pelikhan** [comment]
Currently, some of our drivers use the controlpacket data section. Is this possible in the new scheme?

**Comment by jamesadevine** [comment]
> What is the relation between driverinfo and controlpacket?

`DriverInfo` is embedded in the data field of the control packet. You have as many `DriverInfo` fields as you do drivers

> Currently, some of our drivers use the controlpacket data section. Is this possible in the new scheme?

In every `DriverInfo` field there is an optional payload/data area for additional driver information. The length of the payload is indicated by the length field in each `DriverInfo` 

> Should we bump up the serialnumber number of bytes?

I don't think so. Each driver is no longer required to broadcast its own serial number, so the chances of a collision scale with the number of devices on the bus.

**Comment by pelikhan** [comment]
So the logic driver will route the driver info back to each driver? Looks good.

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by jamesadevine** [comment]
```cpp
struct JDControlPacket
{
    uint32_t serial_number; // the "unique" serial number of the device.
    uint8_t data[];
} __attribute((__packed__));

struct JDDriverInfo
{
    uint8_t size;
    uint8_t address;        // the address assigned by the logic driver
    uint16_t flags: 8, error_code: 4, type: 4; // various flags, upper eight bits are reserved for control usage, error code, then driver info type
    uint32_t driver_class;  // the class of the driver
    uint8_t data[]; // optional additional data
} __attribute((__packed__));
```

Revised packet structure above.

Control Packets will always be a serial number followed by N `DriverInfo` entries.

This means HELLO control packets will look like this:
```
ControlPacket
{
    Serial number: 12345
    [
        {
            size: 0,
            address:20,
            flags: 0,
            error_code: 0,
            type: 1 (HELLO),
            driver_class: ACCELEROMETER
        },
        {
            size: 4,
            address:23,
            flags: 0,
            error_code: 0,
            type: 1 (HELLO),
            driver_class: BUTTON
            data: "BTNA"
        },
        {
            size: 4,
            address:29,
            flags: 0,
            error_code: 0,
            type: 1 (HELLO),
            driver_class: BUTTON
            data: "BTNB"
        }
    ]
}
```

A pairing request control packet would look like:

```
ControlPacket
{
    Serial number: 12345
    [
        {
            size: 10,
            address:20,
            flags: 0,
            error_code: 0,
            type: 2 (PAIRING REQUEST),
            driver_class: ACCELEROMETER
            data: PAIRING_DATA
        }
    ]
}
```
