### ISSUE TITLE
Serial readBuffer looses characters

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-core#89]
If ``bufferIndex < bufferLen`` is false, we lost a character.

https://github.com/lancaster-university/codal-core/blob/master/source/driver-models/Serial.cpp#L653

**Comment by jamesadevine** [comment]
Why is this a bug? It will fill as many bytes as the buffer you give it?

**Comment by pelikhan** [comment]
It consumes a character in "getChar" and drops it because the buffer is full.

**Comment by jamesadevine** [comment]
I see, thanks @pelikhan

**Comment by pelikhan** [comment]
Also ``rxBufferSize()`` does not call ``initializeRx()``. is that ok?

**Comment by pelikhan** [comment]
https://github.com/Microsoft/pxt-maker/issues/150

**Comment by jamesadevine** [comment]
Same bug exists in the DAL... https://github.com/lancaster-university/microbit-dal/blob/master/source/drivers/MicroBitSerial.cpp#L649

**Comment by pelikhan** [comment]
I basically want to read all the data you have and parse it on my side. MakeCode uses UTF8 now.
